package table.queries;

public class TableInserts {

	public static final String INSERT_ACTIONS = "INSERT INTO Action (id_action, action_name, times) VALUES (1, 'pagar', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (2, 'pagar', 50)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (3, 'pagar', 100)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (4, 'pagar', 150)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (5, 'pagar', 200)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (6, 'pagar por jugador', 50)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (7, 'salir carcel', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (8, 'tirar dados', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (9, 'retroceder casillas', 3)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (10, 'retroceder casillas', 5)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (11, 'avanzar casillas', 3)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (12, 'avanzar casillas', 5)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (13, 'sumar dados', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (14, 'ir a salida', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (15, 'cobrar', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (16, 'cobrar', 50)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (17, 'cobrar', 100)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (18, 'cobrar', 150)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (19, 'cobrar', 200)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (20, 'cobrar por jugador', 50)";

	public static final String INSERT_BOARD = "INSERT INTO Board (id_board, size) VALUES (1, 40)";

	public static final String INSERT_CARDS_LUCK = "INSERT INTO Card (id_card, type, action_id) VALUES (1,'LUCK', 1)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (2,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (3,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (4,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (5,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (6,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (7,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (8,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (9,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (10,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (11,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (12,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (13,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (14,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (15,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (16,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (17,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (18,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (19,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (20,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (21,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (22,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (23,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (24,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (25,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (26,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (27,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (28,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (29,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (30,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (31,'LUCK', )"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (32,'LUCK', )";

	public static final String INSERT_CARDS_COMMUNITY_CHEST = "INSERT INTO Card (id_card, type, action_id) VALUES (1,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (2,'COMMUNITY_CHEST', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (3,'COMMUNITY_CHEST', 18)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (4,'COMMUNITY_CHEST', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (5,'COMMUNITY_CHEST', 14)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (6,'COMMUNITY_CHEST', 17)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (7,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (8,'COMMUNITY_CHEST', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (9,'COMMUNITY_CHEST', 20)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (10,'COMMUNITY_CHEST', 5)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (11,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (12,'COMMUNITY_CHEST', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (13,'COMMUNITY_CHEST', 17)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (14,'COMMUNITY_CHEST', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (15,'COMMUNITY_CHEST', 18)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (16,'COMMUNITY_CHEST', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (17,'COMMUNITY_CHEST', 16)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (18,'COMMUNITY_CHEST', 5)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (19,'COMMUNITY_CHEST', 18)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (20,'COMMUNITY_CHEST', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (21,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (22,'COMMUNITY_CHEST', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (23,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (24,'COMMUNITY_CHEST', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (25,'COMMUNITY_CHEST', 20)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (26,'COMMUNITY_CHEST', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (27,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (28,'COMMUNITY_CHEST', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (29,'COMMUNITY_CHEST', 17)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (30,'COMMUNITY_CHEST', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (31,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (32,'COMMUNITY_CHEST', 3)";

	public static final String INSERT_CELLS = "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(1, START, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(2, PROPERTY, 1, 1)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(3, COMMUNITY_CHEST, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(4, PROPERTY, 1, 2)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(5, TAX, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(6, PROPERTY, 1, 3)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(7, PROPERTY, 1, 4)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(8, LUCK, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(9, PROPERTY, 1, 5)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(10, PROPERTY, 1, 6)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(11, JAIL, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(12, PROPERTY, 1, 7)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(13, PROPERTY, 1, 8)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(14, PROPERTY, 1, 9)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(15, PROPERTY, 1, 10)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(16, PROPERTY, 1, 11)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(17, PROPERTY, 1, 12)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(18, COMMUNITY_CHEST, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, roperty_id) VALUES(19, PROPERTY, 1, 13)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(20, PROPERTY, 1, 14)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(21, PARKING, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(22, PROPERTY, 1, 15)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(23, LUCK, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(24, PROPERTY, 1, 16)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(25, PROPERTY, 1, 17)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(26, PROPERTY, 1, 18)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(27, PROPERTY, 1, 19)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(28, PROPERTY, 1, 20)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(29, PROPERTY, 1, 21)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(30, PROPERTY, 1, 22)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(31, JAIL, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(32, PROPERTY, 1, 23)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(33, PROPERTY, 1, 24)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(34, COMMUNITY_CHEST, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(35, PROPERTY, 1, 25)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(36, PROPERTY, 1, 26)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(37, LUCK, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(38, PROPERTY, 1, 27)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(39, TAX, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(40, PROPERTY, 1, 28)";

	public static final String INSERT_PROPERTIES = "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(1, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(2, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(3, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(4, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(5, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(6, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(7, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(8, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(9, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(10, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(11, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(12, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(13, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(14, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(15, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(16, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(17, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(18, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(19, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(20, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(21, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(22, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(23, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(24, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(25, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(26, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(27, , , , , , )"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(28, , , , , , )";

	public static final String INSERT_RENT_HOUSE_VALUES = "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(1, 1, 10)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(1, 2, 30)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(1, 3, 90)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(2, 1, 20)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(2, 2, 60)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(2, 3, 180)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(3, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(3, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(3, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(4, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(4, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(4, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(5, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(5, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(5, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(6, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(6, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(6, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(7, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(7, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(7, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(8, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(8, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(8, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(9, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(9, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(9, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(10, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(10, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(10, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(11, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(11, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(11, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(12, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(12, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(12, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(13, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(13, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(13, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(14, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(14, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(14, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(15, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(15, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(15, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(16, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(16, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(16, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(17, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(17, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(17, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(18, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(18, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(18, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(19, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(19, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(19, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(20, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(20, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(20, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(21, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(21, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(21, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(22, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(22, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(22, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(23, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(23, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(23, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(24, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(24, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(24, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(25, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(25, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(25, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(26, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(26, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(26, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(27, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(27, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(27, 3, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(28, 1, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(28, 2, )"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(28, 3, )";
}