package table.queries;

public class TableInserts {

	public static final String INSERT_ACTIONS = "INSERT INTO Action (id_action, action_name, times) VALUES (1, 'pagar', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (2, 'pagar', 50)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (3, 'pagar', 100)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (4, 'pagar', 150)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (5, 'pagar', 200)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (6, 'pagar por jugador', 50)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (7, 'salir carcel', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (8, 'tirar dados', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (9, 'retroceder casillas', 3)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (10, 'retroceder casillas', 5)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (11, 'avanzar casillas', 3)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (12, 'avanzar casillas', 5)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (13, 'sumar dados', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (14, 'ir a salida', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (15, 'cobrar', 1)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (16, 'cobrar', 50)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (17, 'cobrar', 100)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (18, 'cobrar', 150)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (19, 'cobrar', 200)"
			+ "INSERT INTO Action (id_action, action_name, times) VALUES (20, 'cobrar por jugador', 50)";

	public static final String INSERT_BOARD = "INSERT INTO Board (id_board, size) VALUES (1, 40)";

	public static final String INSERT_CARDS_LUCK = "INSERT INTO Card (id_card, type, action_id) VALUES (1,'LUCK', 1)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (2,'LUCK', 8)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (3,'LUCK', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (4,'LUCK', 15)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (5,'LUCK', 13)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (6,'LUCK', 20)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (7,'LUCK', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (8,'LUCK', 5)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (9,'LUCK', 9)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (10,'LUCK', 16)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (11,'LUCK', 11)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (12,'LUCK', 14)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (13,'LUCK', 7)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (14,'LUCK', 10)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (15,'LUCK', 18)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (16,'LUCK', 1)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (17,'LUCK', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (18,'LUCK', 12)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (19,'LUCK', 12)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (20,'LUCK', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (21,'LUCK', 15)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (22,'LUCK', 14)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (23,'LUCK', 6)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (24,'LUCK', 17)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (25,'LUCK', 9)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (26,'LUCK', 13)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (27,'LUCK', 10)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (28,'LUCK', 11)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (29,'LUCK', 1)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (30,'LUCK', 15)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (31,'LUCK', 20)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (32,'LUCK', 5)";

	public static final String INSERT_CARDS_COMMUNITY_CHEST = "INSERT INTO Card (id_card, type, action_id) VALUES (33,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (34,'COMMUNITY_CHEST', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (35,'COMMUNITY_CHEST', 18)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (36,'COMMUNITY_CHEST', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (37,'COMMUNITY_CHEST', 14)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (38,'COMMUNITY_CHEST', 17)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (39,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (40,'COMMUNITY_CHEST', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (41,'COMMUNITY_CHEST', 20)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (42,'COMMUNITY_CHEST', 5)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (43,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (44,'COMMUNITY_CHEST', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (45,'COMMUNITY_CHEST', 17)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (46,'COMMUNITY_CHEST', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (47,'COMMUNITY_CHEST', 18)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (48,'COMMUNITY_CHEST', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (49,'COMMUNITY_CHEST', 16)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (50,'COMMUNITY_CHEST', 5)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (51,'COMMUNITY_CHEST', 18)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (52,'COMMUNITY_CHEST', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (53,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (54,'COMMUNITY_CHEST', 3)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (55,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (56,'COMMUNITY_CHEST', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (57,'COMMUNITY_CHEST', 20)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (58,'COMMUNITY_CHEST', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (59,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (60,'COMMUNITY_CHEST', 2)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (61,'COMMUNITY_CHEST', 17)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (62,'COMMUNITY_CHEST', 4)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (63,'COMMUNITY_CHEST', 19)"
			+ "INSERT INTO Card (id_card, type, action_id) VALUES (64,'COMMUNITY_CHEST', 3)";

	public static final String INSERT_CELLS = "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(1, START, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(2, PROPERTY, 1, 1)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(3, COMMUNITY_CHEST, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(4, PROPERTY, 1, 2)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(5, TAX, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(6, PROPERTY, 1, 3)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(7, PROPERTY, 1, 4)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(8, LUCK, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(9, PROPERTY, 1, 5)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(10, PROPERTY, 1, 6)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(11, JAIL, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(12, PROPERTY, 1, 7)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(13, PROPERTY, 1, 8)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(14, PROPERTY, 1, 9)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(15, PROPERTY, 1, 10)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(16, PROPERTY, 1, 11)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(17, PROPERTY, 1, 12)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(18, COMMUNITY_CHEST, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, roperty_id) VALUES(19, PROPERTY, 1, 13)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(20, PROPERTY, 1, 14)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(21, PARKING, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(22, PROPERTY, 1, 15)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(23, LUCK, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(24, PROPERTY, 1, 16)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(25, PROPERTY, 1, 17)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(26, PROPERTY, 1, 18)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(27, PROPERTY, 1, 19)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(28, PROPERTY, 1, 20)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(29, PROPERTY, 1, 21)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(30, PROPERTY, 1, 22)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(31, JAIL, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(32, PROPERTY, 1, 23)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(33, PROPERTY, 1, 24)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(34, COMMUNITY_CHEST, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(35, PROPERTY, 1, 25)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(36, PROPERTY, 1, 26)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(37, LUCK, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(38, PROPERTY, 1, 27)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(39, TAX, 1, null)"
			+ "INSERT INTO Cell (id_cell, type, board_id, property_id) VALUES(40, PROPERTY, 1, 28)";

	public static final String INSERT_PROPERTIES = "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(1, 60, 60, 50, 50, 160, 2)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(2, 60, 60, 50, 50, 180, 4)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(3, 100, 100, 50, 50, 400, 6)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(4, 100, 100, 50, 50, 400, 6)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(5, 120, 120, 50, 50, 450, 8)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(6, 140, 140, 100, 100, 625, 10)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(7, 140, 140, 100, 100, 625, 10)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(8, 160, 160, 100, 100, 700, 12)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(9, 180, 180, 100, 100, 750, 14)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(10, 180, 180, 100, 100, 750, 14)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(11, 200, 200, 100, 100, 800, 16)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(12, 220, 220, 150, 150, 875, 18)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(13, 220, 220, 150, 150, 875, 18)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(14, 240, 240, 150, 150, 925, 20)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(15, 260, 260, 150, 150, 975, 22)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(16, 260, 260, 150, 150, 975, 22)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(17, 280, 280, 150, 150, 1025, 24)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(18, 300, 300, 200, 200, 1100, 26)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(19, 300, 300, 200, 200, 1100, 26)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(20, 320, 320, 200, 200, 1200, 28)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(21, 350, 350, 200, 200, 1300, 35)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(22, 400, 400, 200, 200, 1700, 50)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(23, 200, 200, 0, 0, 0, 25)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(24, 200, 200, 0, 0, 0, 25)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(25, 200, 200, 0, 0, 0, 25)"
			+ "INSERT INTO Property (id_property, sell_value, buy_value, house_buy_value, hotel_buy_value, rent_hotel_value, rent_base_value) VALUES(26, 200, 200, 0, 0, 0, 25)";

	public static final String INSERT_RENT_HOUSE_VALUES = "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(1, 1, 10)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(1, 2, 30)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(1, 3, 90)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(2, 1, 20)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(2, 2, 60)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(2, 3, 180)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(3, 1, 30)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(3, 2, 90)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(3, 3, 270)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(4, 1, 30)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(4, 2, 90)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(4, 3, 270)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(5, 1, 40)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(5, 2, 100)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(5, 3, 300)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(6, 1, 50)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(6, 2, 150)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(6, 3, 450)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(7, 1, 50)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(7, 2, 150)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(7, 3, 450)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(8, 1, 60)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(8, 2, 180)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(8, 3, 500)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(9, 1, 70)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(9, 2, 200)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(9, 3, 550)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(10, 1, 70)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(10, 2, 200)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(10, 3, 550)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(11, 1, 80)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(11, 2, 220)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(11, 3, 600)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(12, 1, 90)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(12, 2, 250)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(12, 3, 700)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(13, 1, 90)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(13, 2, 250)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(13, 3, 700)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(14, 1, 100)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(14, 2, 300)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(14, 3, 750)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(15, 1, 110)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(15, 2, 330)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(15, 3, 800)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(16, 1, 110)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(16, 2, 330)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(16, 3, 800)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(17, 1, 120)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(17, 2, 360)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(17, 3, 850)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(18, 1, 130)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(18, 2, 390)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(18, 3, 900)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(19, 1, 130)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(19, 2, 390)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(19, 3, 900)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(20, 1, 150)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(20, 2, 450)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(20, 3, 1000)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(21, 1, 175)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(21, 2, 500)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(21, 3, 1100)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(22, 1, 200)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(22, 2, 600)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(22, 3, 1400)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(23, 1, 50)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(23, 2, 100)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(23, 3, 200)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(24, 1, 50)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(24, 2, 100)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(24, 3, 200)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(25, 1, 50)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(25, 2, 100)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(25, 3, 200)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(26, 1, 50)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(26, 2, 100)"
			+ "INSERT INTO Rent_House_Value (property_id, house_count, rent_value) VALUES(26, 3, 200)";
}